AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for github-actions-with-aws-sam

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  Lambda001:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: python3.10
      Architectures:
        - x86_64
  Lambda001PublicUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt Lambda001.Arn
  Lambda001Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Principal: "*"
      Action: "lambda:InvokeFunctionUrl"
      FunctionName: !GetAtt Lambda001.Arn
      FunctionUrlAuthType: NONE

Outputs:
  Lambda001:
    Description: "Lambda001 ARN"
    Value: !GetAtt Lambda001.Arn
